image: ubuntu:xenial
before_script:
- bash docker_install.sh
build:web:
  script:
  - ls
  - dotnet --info
  - cd src/DomainModel && dotnet restore && dotnet build
  - ls
  - cd .. 
  - ls
  - cd src/DataAccessSqliteProvider && dotnet restore && dotnet build
  - ls
  - cd .. 
  - ls
  - cd src/DataAccessPostgreSqlProvider && dotnet restore && dotnet build
  - ls
  - cd .. 
  - ls
  - cd src/DataAccessMySqlProvider && dotnet restore && dotnet build
  - ls 
  - cd .. 
  - ls
  - cd src/DataAccessMsSqlServerProvider && dotnet restore && dotnet build
  - ls
  - cd .. 
  - ls
  - cd src/AspNet5MultipleProject && dotnet restore && dotnet build
  - ls